### PR TITLE
Basic check for qdrant existence

### PR DESCRIPTION
**Pull request by suryyyansh**
Currently, there is no check for whether the qdrant service is running when running the server. This PR adds a simple check to prevent the server from running without an active service at the specified qdrant port and address.

### CODE REVIEW

**Comment by suryyyansh** [comment]
@apepkuss @alabulei1 Please review this PR and let me know if anything needs changing.

**Comment by suryyyansh** [comment]
I don't understand? Why is the build failing?

**Comment by apepkuss** [comment]
Try the following two commands to see if there's any error/warning in your code:

```bash
cargo +nightly fmt --all -- --check
cargo +nightly clippy --target wasm32-wasi -- -D warnings
```

**Comment by suryyyansh** [comment]
@apepkuss Fixed them! I had no idea we were using clippy.

**Comment by apepkuss** [comment]
@suryyyansh Please resolve the conflicts. Thanks!

**Comment by suryyyansh** [comment]
@apepkuss Please review the changes.

The force pushes were because I accidentally merged my search-api branch.

**Pull request closed without merging**
